# -*- coding: utf-8 -*-
"""Dividend Policy Predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biyXJJEWsIIO2xEj79F4Lh-I5RvEOO3P
"""

! pip install python-dotenv

# In order to load environment variables, import these 2 libraries:
import os
from dotenv import load_dotenv

# Load your environment variables
load_dotenv('.env')  # Load environment variables from the file '.env'
api_key = os.environ.get('API_KEY_FMP')  # Retrieve the value of the environment variable 'api_key'
print(api_key)

# Import the requests library
import requests

# Construct your API request endpoint url
BASE_URL = 'https://financialmodelingprep.com/api/v3'
company_tick = "AAPL"
endpoint_url_dividend = f"{BASE_URL}/historical-price-full/stock_dividend/{company_tick}?apikey={api_key}"

# Send an HTTP GET request to the endpoint URL and store the response
response = requests.get(endpoint_url_dividend)
if response.status_code == 429:
    print("FMP API limit reached")

# Convert json to dictionary object and then a Pandas Dataframe
import pandas as pd
response_dict = response.json()
dividends = pd.DataFrame(response_dict['historical'])
dividends.head()

def get_stock_data(ticker, start_date, end_date):
    base_url = f'https://financialmodelingprep.com/api/v3/historical-price-full/{ticker}?'
    params = {'apikey': api_key, 'from': start_date, 'to': end_date}

    response = requests.get(base_url, params=params)
    if response.status_code == 200:
        data = response.json()['historical']
        df = pd.DataFrame(data)
        return df
    else:
        print(f"Error: {response.status_code}")
        return None

# test
ticker = 'AAPL'  #test ticker symbol - apple
start_date = '2024-01-01'
end_date = '2024-04-01'

stock_df = get_stock_data(ticker, start_date, end_date)
print(stock_df)